// Code generated by protoc-gen-micro. DO NOT EDIT.
// source: idgen.proto

/*
Package idgen is a generated protocol buffer package.

It is generated from these files:
	idgen.proto

It has these top-level messages:
	Response
	Req
*/
package idgen

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

import (
	client "github.com/micro/go-micro/client"
	server "github.com/micro/go-micro/server"
	context "context"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ client.Option
var _ server.Option

// Client API for IdGenService service

type IdGenServiceClient interface {
	GetId(ctx context.Context, in *Req, opts ...client.CallOption) (*Response, error)
}

type idGenServiceClient struct {
	c           client.Client
	serviceName string
}

func NewIdGenServiceClient(serviceName string, c client.Client) IdGenServiceClient {
	if c == nil {
		c = client.NewClient()
	}
	if len(serviceName) == 0 {
		serviceName = "idgen"
	}
	return &idGenServiceClient{
		c:           c,
		serviceName: serviceName,
	}
}

func (c *idGenServiceClient) GetId(ctx context.Context, in *Req, opts ...client.CallOption) (*Response, error) {
	req := c.c.NewRequest(c.serviceName, "IdGenService.GetId", in)
	out := new(Response)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Server API for IdGenService service

type IdGenServiceHandler interface {
	GetId(context.Context, *Req, *Response) error
}

func RegisterIdGenServiceHandler(s server.Server, hdlr IdGenServiceHandler, opts ...server.HandlerOption) {
	s.Handle(s.NewHandler(&IdGenService{hdlr}, opts...))
}

type IdGenService struct {
	IdGenServiceHandler
}

func (h *IdGenService) GetId(ctx context.Context, in *Req, out *Response) error {
	return h.IdGenServiceHandler.GetId(ctx, in, out)
}
