// Code generated by protoc-gen-go. DO NOT EDIT.
// source: idgen.proto

/*
Package idgen is a generated protocol buffer package.

It is generated from these files:
	idgen.proto

It has these top-level messages:
	Response
	Req
*/
package idgen

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

// 返回值
type Response struct {
	Id uint64 `protobuf:"varint,1,opt,name=Id" json:"Id,omitempty"`
}

func (m *Response) Reset()                    { *m = Response{} }
func (m *Response) String() string            { return proto.CompactTextString(m) }
func (*Response) ProtoMessage()               {}
func (*Response) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

func (m *Response) GetId() uint64 {
	if m != nil {
		return m.Id
	}
	return 0
}

//
type Req struct {
	// 登陆
	MId int32 `protobuf:"varint,1,opt,name=MId" json:"MId,omitempty"`
}

func (m *Req) Reset()                    { *m = Req{} }
func (m *Req) String() string            { return proto.CompactTextString(m) }
func (*Req) ProtoMessage()               {}
func (*Req) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

func (m *Req) GetMId() int32 {
	if m != nil {
		return m.MId
	}
	return 0
}

func init() {
	proto.RegisterType((*Response)(nil), "idgen.Response")
	proto.RegisterType((*Req)(nil), "idgen.Req")
}

func init() { proto.RegisterFile("idgen.proto", fileDescriptor0) }

var fileDescriptor0 = []byte{
	// 133 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0xe2, 0xce, 0x4c, 0x49, 0x4f,
	0xcd, 0xd3, 0x2b, 0x28, 0xca, 0x2f, 0xc9, 0x17, 0x62, 0x05, 0x73, 0x94, 0xa4, 0xb8, 0x38, 0x82,
	0x52, 0x8b, 0x0b, 0xf2, 0xf3, 0x8a, 0x53, 0x85, 0xf8, 0xb8, 0x98, 0x3c, 0x53, 0x24, 0x18, 0x15,
	0x18, 0x35, 0x58, 0x82, 0x98, 0x3c, 0x53, 0x94, 0xc4, 0xb9, 0x98, 0x83, 0x52, 0x0b, 0x85, 0x04,
	0xb8, 0x98, 0x7d, 0xa1, 0xe2, 0xac, 0x41, 0x20, 0xa6, 0x91, 0x19, 0x17, 0x8f, 0x67, 0x8a, 0x7b,
	0x6a, 0x5e, 0x70, 0x6a, 0x51, 0x59, 0x66, 0x72, 0xaa, 0x90, 0x1a, 0x17, 0xab, 0x7b, 0x6a, 0x89,
	0x67, 0x8a, 0x10, 0x97, 0x1e, 0xc4, 0x8a, 0xa0, 0xd4, 0x42, 0x29, 0x7e, 0x38, 0x1b, 0x62, 0xbc,
	0x12, 0x43, 0x12, 0x1b, 0xd8, 0x6a, 0x63, 0x40, 0x00, 0x00, 0x00, 0xff, 0xff, 0xc4, 0x69, 0x6c,
	0xb2, 0x89, 0x00, 0x00, 0x00,
}
